apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nkp-nutanix-<VERSION>.yaml

patches:
- path: cis-mitigations-cp-patch.yaml
- target:
    group: controlplane.cluster.x-k8s.io
    version: v1beta1
    kind: KubeadmControlPlaneTemplate
    #target <2.15.0
    name: nkp-nutanix-v2.1[0-4].*
    namespace: <NAMESPACE>
  patch: |
    #so that it works in v2.14.0. Make sure to remove after to 2.14.0
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/files
      value: []
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/files/-
      value:
        path: /etc/kubernetes/admission/admissionConfiguration.yaml
        permissions: "0600"
        content: |
          apiVersion: apiserver.config.k8s.io/v1
          kind: AdmissionConfiguration
          plugins:
          - name: EventRateLimit
            path: /etc/kubernetes/admission/eventRateLimit.yaml
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/files/-
      value:
        path: /etc/kubernetes/admission/eventRateLimit.yaml
        permissions: "0600"
        content: |
          apiVersion: eventratelimit.admission.k8s.io/v1alpha1
          kind: Configuration
          limits:
          - type: Server
            qps: 5000
            burst: 20000
          - type: Namespace
            qps: 500
            burst: 2000
            cacheSize: 1000
          - type: User
            qps: 100
            burst: 400
            cacheSize: 2000
          - type: SourceAndObject
            qps: 50
            burst: 100
            cacheSize: 5000
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/postKubeadmCommands/-
      value: 'chmod 600 "$(systemctl show -P FragmentPath kubelet.service)"'
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/postKubeadmCommands/-
      value: 'chmod 600 /var/lib/kubelet/config.yaml'
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/postKubeadmCommands/-
      value: 'echo "serverTLSBootstrap: true" >> /var/lib/kubelet/config.yaml'
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/postKubeadmCommands/-
      value: 'chmod 600 /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf'

- target:
    group: controlplane.cluster.x-k8s.io
    version: v1beta1
    kind: KubeadmControlPlaneTemplate
    #target only NKP => v2.15.0
    name: nkp-nutanix-v2.1[5-9].* 
    namespace: <NAMESPACE>
  patch: |
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/files/-
      value:
        path: /etc/kubernetes/admission/admissionConfiguration.yaml
        permissions: "0600"
        content: |
          apiVersion: apiserver.config.k8s.io/v1
          kind: AdmissionConfiguration
          plugins:
          - name: EventRateLimit
            path: /etc/kubernetes/admission/eventRateLimit.yaml
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/files/-
      value:
        path: /etc/kubernetes/admission/eventRateLimit.yaml
        permissions: "0600"
        content: |
          apiVersion: eventratelimit.admission.k8s.io/v1alpha1
          kind: Configuration
          limits:
          - type: Server
            qps: 5000
            burst: 20000
          - type: Namespace
            qps: 500
            burst: 2000
            cacheSize: 1000
          - type: User
            qps: 100
            burst: 400
            cacheSize: 2000
          - type: SourceAndObject
            qps: 50
            burst: 100
            cacheSize: 5000
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/postKubeadmCommands/-
      value: 'chmod 600 "$(systemctl show -P FragmentPath kubelet.service)"'
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/postKubeadmCommands/-
      value: 'chmod 600 /var/lib/kubelet/config.yaml'
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/postKubeadmCommands/-
      value: 'echo "serverTLSBootstrap: true" >> /var/lib/kubelet/config.yaml'
    - op: add
      path: /spec/template/spec/kubeadmConfigSpec/postKubeadmCommands/-
      value: 'chmod 600 /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf'
namePrefix: ""
nameSuffix: "-hardened"
