apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nkp-nutanix-worker-<VERSION>.yaml

patches:
- path: cis-mitigations-worker-patch.yaml

namePrefix: ""
nameSuffix: "-hardened"
