apiVersion: v1
entries:
  capi-runtime-extensions:
  - apiVersion: v2
    appVersion: v0.3.1
    created: "2024-02-08T12:33:53.108217Z"
    description: A Helm chart for capi-runtime-extensions
    digest: 1a200a5d107bf6849524a124bf442061682334cc9ad34befa1f67e5a345ffbd7
    home: https://github.com/d2iq-labs/capi-runtime-extensions
    maintainers:
    - email: jimmidyson@gmail.com
      name: jimmidyson
      url: https://eng.d2iq.com
    name: capi-runtime-extensions
    sources:
    - https://github.com/d2iq-labs/capi-runtime-extensions
    type: application
    urls:
    - https://github.com/d2iq-labs/capi-runtime-extensions/releases/download/v0.3.1/capi-runtime-extensions-v0.3.1.tgz
    version: v0.3.1
generated: "2024-02-08T12:37:21.044242Z"
