# Copyright 2021-2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write
  actions: write

defaults:
  run:
    shell: bash

jobs:
  release-tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0
        with:
          enable-cache: true

      - name: Go cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: devbox run -- make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart and attach to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          devbox run -- helm package ./charts/capi-runtime-extensions \
                          --destination . \
                          --version ${{ github.ref_name }} \
                          --app-version ${{ github.ref_name }}
          devbox run -- gh release upload ${{ github.ref_name }} capi-runtime-extensions-*.tgz

      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Update and commit Helm index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: ./docs/static/helm/index.yaml
        run: |
          devbox run -- helm repo index . \
            --url "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}" \
            --merge "${FILE_TO_COMMIT}"
          mv index.yaml "${FILE_TO_COMMIT}"
          MESSAGE="build(${{ github.ref_name }}): Update Helm index"
          SHA=$( git rev-parse "main":"${FILE_TO_COMMIT}" )
          gh api --method PUT "/repos/:owner/:repo/contents/${FILE_TO_COMMIT}" \
            --field message="${MESSAGE}" \
            --field content=@<( base64 -i "${FILE_TO_COMMIT}" ) \
            --field encoding="base64" \
            --field branch="main" \
            --field sha="${SHA}"

      - name: Build GitHub pages
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: github-pages.yml
